version: '3'


services:

  manticore:
    image: manticoresearch/manticore:7.4.6
    environment:
      EXTRA: 1
      # Will attempt to index 'gamenode' on startup
      CREATE_PLAIN_TABLES: gamenode

    restart: no
    ports:
      # Note: ManticoreSearch as minimum built-in security,
      # so it's not recommended to expose it to the host in production.
      # SQL port, use it with care.
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"

    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1

    volumes:
      - manticore:/var/lib/manticore
      - ./manticore.conf:/etc/manticoresearch/manticore.conf

    network_mode: host


volumes:
  manticore:

