// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "gamenode.com.br/help",
            "email": "support@gamenode.com.br"
        },
        "license": {
            "name": "GNU General Public License",
            "url": "http://www.gnu.org/licenses/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/search/games": {
            "post": {
                "description": "Returns a parsed search response from the Manticore engine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Searches for games using Manticore engine",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/games.GameSearchRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/games.GameSearchResponseDto"
                        }
                    }
                }
            }
        },
        "/search/games/autocomplete": {
            "post": {
                "description": "Returns a parsed search response from the Manticore engine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Autocomplete games names using Manticore engine",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/games.GameSearchRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/games.GameAutocompleteResponseDto"
                        }
                    }
                }
            }
        },
        "/search/users": {
            "post": {
                "description": "Returns a parsed search response from the Manticore engine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Searches for users using Manticore engine",
                "parameters": [
                    {
                        "description": "Account ID",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.UserSearchRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users.UserSearchResponseDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "games.GameAutocompleteResponseDto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "games.GameSearchRequestDto": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "platforms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile": {
                    "type": "boolean"
                },
                "query": {
                    "type": "string"
                },
                "status": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "themes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "games.GameSearchResponseDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/games.ResponseData"
                },
                "pagination": {
                    "$ref": "#/definitions/schema.PaginationInfo"
                }
            }
        },
        "games.ResponseData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/games.SearchGame"
                    }
                },
                "profile": {
                    "type": "object",
                    "additionalProperties": true
                },
                "took": {
                    "type": "integer"
                }
            }
        },
        "games.SearchGame": {
            "type": "object",
            "properties": {
                "aggregatedRating": {
                    "type": "number"
                },
                "aggregatedRatingCount": {
                    "type": "integer"
                },
                "category": {
                    "type": "integer"
                },
                "checksum": {
                    "type": "string"
                },
                "coverUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "firstReleaseDate": {
                    "type": "string"
                },
                "genresNames": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keywordsNames": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "numLikes": {
                    "type": "integer"
                },
                "numViews": {
                    "type": "integer"
                },
                "platformsAbbreviations": {
                    "type": "string"
                },
                "platformsNames": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "storyline": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "themesNames": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "schema.PaginationInfo": {
            "type": "object",
            "properties": {
                "hasNextPage": {
                    "type": "boolean"
                },
                "totalItems": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "users.UserDto": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "users.UserSearchRequestDto": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "users.UserSearchResponseData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/users.UserDto"
                    }
                },
                "profile": {
                    "type": "object",
                    "additionalProperties": true
                },
                "took": {
                    "type": "integer"
                }
            }
        },
        "users.UserSearchResponseDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/users.UserSearchResponseData"
                },
                "pagination": {
                    "$ref": "#/definitions/schema.PaginationInfo"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GameNode Search API",
	Description:      "The GameNode Search API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
